<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) LOCKON CO.,LTD. All Rights Reserved.
 *
 * http://www.lockon.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\colorselect\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\colorselect\Entity\ColorselectConfig;
use Plugin\colorselect\Entity\ProductReviewConfig;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ColorselectConfigRepository Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColorselectConfigRepository extends AbstractRepository
{
    /**
     * ColorselectConfigRepogitory constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, ColorselectConfig::class);
    }

    /**
     * @param int $id
     *
     * @return null|ColorselectConfig
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
